### ISSUE TITLE
Idea: Save and Open Z files - [export as a file method]

### ISSUE THREAD

**Issue by EddyMM** [Z-Editor/Z-Editor#17]
After writing down a specification, it would be helpful if I could download the specification in **a format that I can import back to the editor** later on if need be. (May be XML, JSON, etc)

A PDF, while useful for reference purposes, cannot be edited.

**Comment by nadunindunil** [comment]
Hi,
Thanks @EddyMM for your suggestions. Actually that's a good idea.
I will work on that  :+1:

**Comment by nadunindunil** [comment]
Hi @EddyMM ,
I happy to announce that your request is completed as in #25 PR
Thank you very much for the suggestion

I will add the latest version in as soon as possible.
