### ISSUE TITLE
Landing Page for the tool

### ISSUE THREAD

**Issue by nadunindunil** [Z-Editor/Z-Editor#3]
It would be nice to have a landing page and description about project to show the world what we have done. why don't you come up with an innovative idea.

**Comment by mahmedov** [comment]
Hello, I'll see if I can make a landing page for Z-Editor.

**Comment by nadunindunil** [comment]
Hi @mahmedov ,
You can be creative as you wish in this issue.
my first idea was creating a gh-pages branch and making jekyll landing page.(with contribution guide and readme and description about the project)
something more like [this](http://www.landingfolio.com/gallery/software/electron/)
feel free to comment if you have different ideas.

**Comment by kylemcd** [comment]
Hey! If you can provide a place in the repo for this to be done I could take a crack at it 💯

**Comment by nadunindunil** [comment]
Hi @kylemcd , 
perhaps you can start it in a different branch then I can merge it to a branch like gh-pages in main repo.

**Comment by mahmedov** [comment]
Hey sorry for a late response but I had some things to care of.
