### ISSUE TITLE
[Bug] EditorState doesn't update state after uploading a file

### ISSUE THREAD

**Issue by shehabadel** [Z-Editor/Z-Editor#61]
### Description

`downloadState` will not update its state after uploading a file unless we start modifying it. A simple use-case is if I uploaded a file, then tried to download it immediately without any modifications, it will download an empty file.

### Steps to Reproduce

1. Update the `downloadState` after immediately uploading the file.

**Expected behavior:** 

- After uploading the file and downloading it immediately without any modifications. It will download the same file again

**Actual behavior:** 

- After uploading the file and downloading it immediately without any modifications. It will download an **Empty file**.

**Comment by nadunindunil** [comment]
Hi @shehabadel ,
I am closing this issue since we merged the fix.
