### ISSUE TITLE
Auto-deploy the tool into z-editor.github.io

### ISSUE THREAD

**Issue by nadunindunil** [Z-Editor/Z-Editor#7]
right now we are building the project in local after every commit and push the built (updated) version to [z-editor.github.io](https://github.com/Z-Editor/z-editor.github.io) repo.

propose a method to auto deploy the built version of the tool.
you may use travic ci.

[help 1](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd)
[help 2](https://docs.travis-ci.com/user/deployment/pages/)

**Comment by marceloabk** [comment]
I'll try to work on this one
